/**
 * Simple Test Workflow
 *
 * Minimal workflow for testing the workflow engine.
 * No args, just writes a random file for git commit testing.
 *
 * Features:
 * - 2 phases (Research → Write)
 * - Agent steps with JSON responses
 * - Annotations for progress
 * - Random file generation
 * - Logging
 */

import { defineWorkflow } from "agentcmd-workflows";

// Type-safe wrappers for slash commands defined in .claude/commands/
// After editing commands, regenerate: npx agentcmd-workflows generate-slash-types
import {
  buildSlashCommand,
  type CmdCreatePrResponse,
} from "../../generated/slash-commands";

// Prompts
const RESEARCH_PROMPT = (topic: string) => `Research the topic: "${topic}"

Return JSON with:
{
  "topic": "${topic}",
  "facts": ["3-5 interesting facts about the topic"],
  "interestingPoints": number (1-10 rating)
}

Note: This is a TEST workflow - keep response brief and generic.`;

const WRITE_PROMPT = (topic: string) => `Write a brief article about "${topic}"

Return JSON with:
{
  "title": "article title",
  "content": "2-3 paragraphs of content in markdown format",
  "wordCount": number
}

Note: This is a TEST workflow - keep it simple and brief.`;

const FILE_CONTENT = (params: {
  title?: string;
  content?: string;
  wordCount?: number;
  topic: string;
  timestamp: string;
}) => `# ${params.title || `Article about ${params.topic}`}

${
  params.content ||
  `This is a test article about ${params.topic}.

Generated at: ${new Date().toISOString()}

Random number: ${Math.random().toString(36).substring(7)}

## Test Data
- Topic: ${params.topic}
- Timestamp: ${params.timestamp}
- Word Count: ${params.wordCount || 50}

This file was generated by the demo-simple-test workflow for testing purposes.
`
}`;

export default defineWorkflow(
  {
    id: "demo-simple-test",
    name: "Simple Test Workflow",
    description:
      "Minimal workflow for testing - writes random file for git testing",
    phases: [
      { id: "research", label: "Research" },
      { id: "write", label: "Write" },
      { id: "complete", label: "Complete " },
    ],
  },
  async ({ event, step }) => {
    const { workingDir, specFile } = event.data;

    // Generate random topic for variety
    const topics = [
      "space exploration",
      "quantum computing",
      "deep sea creatures",
      "ancient civilizations",
      "renewable energy",
    ];
    const randomTopic = topics[Math.floor(Math.random() * topics.length)];
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");

    // ========================================
    // PHASE 1: Research
    // ========================================
    await step.phase("research", async () => {
      await step.annotation("start-research", {
        message: `Researching topic: ${randomTopic}. During this step, we're going to dig into the topic and gather some facts about it.`,
      });

      const researchResult = await step.agent<{
        topic: string;
        facts: string[];
        interestingPoints: number;
      }>("research-topic", {
        agent: "claude",
        json: true,
        prompt: RESEARCH_PROMPT(randomTopic),
        workingDir,
      });

      await step.annotation("research-complete", {
        message: `Found ${
          researchResult.data.facts?.length || 3
        } facts about ${randomTopic}`,
      });

      // Log research results
      console.log(
        `[Research] Topic: ${randomTopic}, Facts: ${
          researchResult.data.facts?.length || 3
        }`
      );
    });

    // ========================================
    // PHASE 2: Write
    // ========================================
    await step.phase("write", async () => {
      await step.annotation("start-writing", {
        message: "Writing content file",
      });

      const writeResult = await step.agent<{
        title: string;
        content: string;
        wordCount: number;
      }>("write-content", {
        agent: "claude",
        json: true,
        prompt: WRITE_PROMPT(randomTopic),
        workingDir,
      });

      // Create random test file
      const filename = `test-article-${timestamp}.md`;
      const filepath = `${workingDir}/.agent/generated/${filename}`;

      const fileContent = FILE_CONTENT({
        title: writeResult.data.title,
        content: writeResult.data.content,
        wordCount: writeResult.data.wordCount,
        topic: randomTopic,
        timestamp,
      });

      await step.cli("write-file", {
        command: `mkdir -p .agent/generated && cat > .agent/generated/${filename} << 'EOF'
${fileContent}
EOF`,
        cwd: workingDir,
      });

      await step.annotation("write-complete", {
        message: `Created ${filename} (${
          writeResult.data.wordCount || 50
        } words)`,
      });

      console.log(
        `[Write] Created: ${filename}, Words: ${
          writeResult.data.wordCount || 50
        }`
      );

      // Create artifact
      await step.artifact("content-summary", {
        name: "content-summary.json",
        type: "text",
        content: JSON.stringify(
          {
            filename,
            topic: randomTopic,
            title: writeResult.data.title,
            wordCount: writeResult.data.wordCount || 50,
            timestamp: new Date().toISOString(),
          },
          null,
          2
        ),
      });

      await step.annotation("workflow-complete", {
        message: `✓ Workflow complete - file ready for git testing`,
      });
    });

    await step.phase("complete", async () => {
      // Move spec to done folder and updates index.json
      await step.agent("complete-spec", {
        agent: "claude",
        prompt: buildSlashCommand("/cmd:move-spec", {
          specIdOrNameOrPath: specFile,
          targetFolder: "done",
        }),
      });

      // Option 2: Use step.agent with /cmd:create-pr (more flexible, handles commit+push+pr)
      const prResult = await step.agent<CmdCreatePrResponse>(
        "commit-push-and-create-pr",
        {
          agent: "claude",
          json: true,
          prompt: buildSlashCommand("/cmd:create-pr", {
            title: `feat: ${event.data.name}`,
          }),
        }
      );

      if (!prResult.data.success) {
        throw new Error(`PR creation failed: ${prResult.data.message}`);
      }

      await step.updateRun({ pr_url: prResult.data.pr_url });
    });

    // Return summary
    return {
      success: true,
      topic: randomTopic,
      timestamp,
      phasesCompleted: 2,
      completedAt: new Date().toISOString(),
    };
  }
);
